### ISSUE TITLE
Game crashes a few seconds after loading.

### ISSUE THREAD

**Issue by wwfdoiewokderdewd** [Fedoraware/Fedoraloader#2] opened 2023-09-28 03:03 UTC
It doesn't do it on the older one though.

**Comment by Fraudly** [comment] 2023-09-28 10:24
same
[https://www.youtube.com/watch?v=teJvA_mB9ns](url)

**Comment by lnx00** [comment] 2023-09-28 11:46
Hmm that's weird. Does it also happen without `-usebypass`?

> same https://www.youtube.com/watch?v=teJvA_mB9ns

Did you manually launch Steam at 00:35? Could you try not launching Steam and waiting for Fedoraloader to open it instead?

**Comment by Fraudly** [comment] 2023-09-28 15:27
> Hmm that's weird. Does it also happen without `-usebypass`?
> 
> > same https://www.youtube.com/watch?v=teJvA_mB9ns
> 
> Did you manually launch Steam at 00:35? Could you try not launching Steam and waiting for Fedoraloader to open it instead?

No, I ran it myself on the video. But I thought I'd check what you said. It started the steam by itself. But then the same thing happened, the game crashed.

**Comment by wwfdoiewokderdewd** [comment] 2023-09-29 03:52
It happens without -usebypass as well, but I prefer -usebypass, its weird, because on the old loader it works fine.

**Comment by wwfdoiewokderdewd** [comment] 2023-09-29 03:58
> same https://www.youtube.com/watch?v=teJvA_mB9ns

That's the EXACT problem I'm having, I tried basically every startup option, for some reason it ONLY works on v1.6.2.

**Comment by lnx00** [comment] 2023-09-29 18:05
I'm still not able to reproduce the crash, even with the game launch parameters :/
Did you add the loader to the anti virus exceptions (Windows Defender, Kaspersky, etc.) so it doesn't tamper with it?

If you did, could you please try this version of the loader and report if it crashes too? This build skips some steps after the injection:
[Fedoraloader_Test1.zip](https://github.com/Fedoraware/Fedoraloader/files/12769982/Fedoraloader_Test1.zip)

**Comment by Fraudly** [comment] 2023-09-29 19:49
> I'm still not able to reproduce the crash, even with the game launch parameters :/ Did you add the loader to the anti virus exceptions (Windows Defender, Kaspersky, etc.) so it doesn't tamper with it?
> 
> If you did, could you please try this version of the loader and report if it crashes too? This build skips some steps after the injection: [Fedoraloader_Test1.zip](https://github.com/Fedoraware/Fedoraloader/files/12769982/Fedoraloader_Test1.zip)

I have a whole flash drive in antivirus exclusion, meaning it doesn't check other disks I have. Still crashes even with your version.

**Comment by lnx00** [comment] 2023-09-29 19:55
I was able to reproduce the issue by running TF2 inside a VM. But I haven't found the cause yet...

**Comment by Fraudly** [comment] 2023-09-29 20:03
> I was able to reproduce the issue by running TF2 inside a VM. But I haven't found the cause yet...

Maybe you can still help information that I have a refresh rate of 75hz on the monitor, and the settings in 3D settings nvidia such:
Low latency mode - ultra
Shader Cache Size - Unlimited
Vertical sync - Fast
Multi-Frame Sampled AA (MFAA) - On
Power management mode - prefer maximum performance

**Comment by lnx00** [comment] 2023-09-30 00:32
Alright, i found the cause, but the fix isn't that easy.
The crash comes occurs when Fedoraware fails to load a config file. And since the loader doesn't handle exceptions yet, the game simply crashes.

**Comment by wwfdoiewokderdewd** [comment] 2023-09-30 02:30
> Alright, i found the cause, but the fix isn't that easy. The crash comes occurs when Fedoraware fails to load a config file. And since the loader doesn't handle exceptions yet, the game simply crashes.

Hmm, Alright, I'm not doing any config files though, thats weird.

**Comment by Fraudly** [comment] 2023-09-30 06:42
> > Alright, i found the cause, but the fix isn't that easy. The crash comes occurs when Fedoraware fails to load a config file. And since the loader doesn't handle exceptions yet, the game simply crashes.
> 
> Hmm, Alright, I'm not doing any config files though, thats weird.

same

**Comment by lnx00** [comment] 2023-09-30 20:55
I have pushed a fix to Fedoraware that should prevent this specific crash for now. Still working on fixing the actual cause though.

**Comment by lnx00** [comment] 2023-10-02 01:05
The issue has been fixed in the latest release.

**Closed by lnx00** 2023-10-02 01:05 UTC

**Comment by wwfdoiewokderdewd** [comment] 2023-10-02 01:13
Wonderful, thank you!
